package com.knewone.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.knewone.dao.Things;

import com.knewone.dao.ThingsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig thingsDaoConfig;

    private final ThingsDao thingsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        thingsDaoConfig = daoConfigMap.get(ThingsDao.class).clone();
        thingsDaoConfig.initIdentityScope(type);

        thingsDao = new ThingsDao(thingsDaoConfig, this);

        registerDao(Things.class, thingsDao);
    }
    
    public void clear() {
        thingsDaoConfig.getIdentityScope().clear();
    }

    public ThingsDao getThingsDao() {
        return thingsDao;
    }

}
