package com.knewone.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table THINGS.
 */
public class Things {

    private Long id;
    private String thingsid;
    private String title;
    private String subtitle;
    private String cover_url;
    private String fanciers_count;
    private String author_avatar;
    private String author_name;
    private String author_id;

    public Things() {
    }

    public Things(Long id) {
        this.id = id;
    }

    public Things(Long id, String thingsid, String title, String subtitle, String cover_url, String fanciers_count, String author_avatar, String author_name, String author_id) {
        this.id = id;
        this.thingsid = thingsid;
        this.title = title;
        this.subtitle = subtitle;
        this.cover_url = cover_url;
        this.fanciers_count = fanciers_count;
        this.author_avatar = author_avatar;
        this.author_name = author_name;
        this.author_id = author_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getThingsid() {
        return thingsid;
    }

    public void setThingsid(String thingsid) {
        this.thingsid = thingsid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public String getCover_url() {
        return cover_url;
    }

    public void setCover_url(String cover_url) {
        this.cover_url = cover_url;
    }

    public String getFanciers_count() {
        return fanciers_count;
    }

    public void setFanciers_count(String fanciers_count) {
        this.fanciers_count = fanciers_count;
    }

    public String getAuthor_avatar() {
        return author_avatar;
    }

    public void setAuthor_avatar(String author_avatar) {
        this.author_avatar = author_avatar;
    }

    public String getAuthor_name() {
        return author_name;
    }

    public void setAuthor_name(String author_name) {
        this.author_name = author_name;
    }

    public String getAuthor_id() {
        return author_id;
    }

    public void setAuthor_id(String author_id) {
        this.author_id = author_id;
    }

}
